/*
Copyright The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	"context"
	json "encoding/json"
	"fmt"

	v1 "github.com/pranoyk/volume-snapshotter/pkg/apis/pranoykundu.dev/v1"
	pranoykundudevv1 "github.com/pranoyk/volume-snapshotter/pkg/client/applyconfiguration/pranoykundu.dev/v1"
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	labels "k8s.io/apimachinery/pkg/labels"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	testing "k8s.io/client-go/testing"
)

// FakeSnapshotActions implements SnapshotActionInterface
type FakeSnapshotActions struct {
	Fake *FakePranoykunduV1
	ns   string
}

var snapshotactionsResource = v1.SchemeGroupVersion.WithResource("snapshotactions")

var snapshotactionsKind = v1.SchemeGroupVersion.WithKind("SnapshotAction")

// Get takes name of the snapshotAction, and returns the corresponding snapshotAction object, and an error if there is any.
func (c *FakeSnapshotActions) Get(ctx context.Context, name string, options metav1.GetOptions) (result *v1.SnapshotAction, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewGetAction(snapshotactionsResource, c.ns, name), &v1.SnapshotAction{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1.SnapshotAction), err
}

// List takes label and field selectors, and returns the list of SnapshotActions that match those selectors.
func (c *FakeSnapshotActions) List(ctx context.Context, opts metav1.ListOptions) (result *v1.SnapshotActionList, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewListAction(snapshotactionsResource, snapshotactionsKind, c.ns, opts), &v1.SnapshotActionList{})

	if obj == nil {
		return nil, err
	}

	label, _, _ := testing.ExtractFromListOptions(opts)
	if label == nil {
		label = labels.Everything()
	}
	list := &v1.SnapshotActionList{ListMeta: obj.(*v1.SnapshotActionList).ListMeta}
	for _, item := range obj.(*v1.SnapshotActionList).Items {
		if label.Matches(labels.Set(item.Labels)) {
			list.Items = append(list.Items, item)
		}
	}
	return list, err
}

// Watch returns a watch.Interface that watches the requested snapshotActions.
func (c *FakeSnapshotActions) Watch(ctx context.Context, opts metav1.ListOptions) (watch.Interface, error) {
	return c.Fake.
		InvokesWatch(testing.NewWatchAction(snapshotactionsResource, c.ns, opts))

}

// Create takes the representation of a snapshotAction and creates it.  Returns the server's representation of the snapshotAction, and an error, if there is any.
func (c *FakeSnapshotActions) Create(ctx context.Context, snapshotAction *v1.SnapshotAction, opts metav1.CreateOptions) (result *v1.SnapshotAction, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewCreateAction(snapshotactionsResource, c.ns, snapshotAction), &v1.SnapshotAction{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1.SnapshotAction), err
}

// Update takes the representation of a snapshotAction and updates it. Returns the server's representation of the snapshotAction, and an error, if there is any.
func (c *FakeSnapshotActions) Update(ctx context.Context, snapshotAction *v1.SnapshotAction, opts metav1.UpdateOptions) (result *v1.SnapshotAction, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateAction(snapshotactionsResource, c.ns, snapshotAction), &v1.SnapshotAction{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1.SnapshotAction), err
}

// Delete takes name of the snapshotAction and deletes it. Returns an error if one occurs.
func (c *FakeSnapshotActions) Delete(ctx context.Context, name string, opts metav1.DeleteOptions) error {
	_, err := c.Fake.
		Invokes(testing.NewDeleteActionWithOptions(snapshotactionsResource, c.ns, name, opts), &v1.SnapshotAction{})

	return err
}

// DeleteCollection deletes a collection of objects.
func (c *FakeSnapshotActions) DeleteCollection(ctx context.Context, opts metav1.DeleteOptions, listOpts metav1.ListOptions) error {
	action := testing.NewDeleteCollectionAction(snapshotactionsResource, c.ns, listOpts)

	_, err := c.Fake.Invokes(action, &v1.SnapshotActionList{})
	return err
}

// Patch applies the patch and returns the patched snapshotAction.
func (c *FakeSnapshotActions) Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts metav1.PatchOptions, subresources ...string) (result *v1.SnapshotAction, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewPatchSubresourceAction(snapshotactionsResource, c.ns, name, pt, data, subresources...), &v1.SnapshotAction{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1.SnapshotAction), err
}

// Apply takes the given apply declarative configuration, applies it and returns the applied snapshotAction.
func (c *FakeSnapshotActions) Apply(ctx context.Context, snapshotAction *pranoykundudevv1.SnapshotActionApplyConfiguration, opts metav1.ApplyOptions) (result *v1.SnapshotAction, err error) {
	if snapshotAction == nil {
		return nil, fmt.Errorf("snapshotAction provided to Apply must not be nil")
	}
	data, err := json.Marshal(snapshotAction)
	if err != nil {
		return nil, err
	}
	name := snapshotAction.Name
	if name == nil {
		return nil, fmt.Errorf("snapshotAction.Name must be provided to Apply")
	}
	obj, err := c.Fake.
		Invokes(testing.NewPatchSubresourceAction(snapshotactionsResource, c.ns, *name, types.ApplyPatchType, data), &v1.SnapshotAction{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1.SnapshotAction), err
}
