/*
Copyright The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	"context"
	json "encoding/json"
	"fmt"

	v1 "github.com/pranoyk/volume-snapshotter/pkg/apis/pranoykundu.dev/v1"
	pranoykundudevv1 "github.com/pranoyk/volume-snapshotter/pkg/client/applyconfiguration/pranoykundu.dev/v1"
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	labels "k8s.io/apimachinery/pkg/labels"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	testing "k8s.io/client-go/testing"
)

// FakeSnapshotActionses implements SnapshotActionsInterface
type FakeSnapshotActionses struct {
	Fake *FakePranoykunduV1
	ns   string
}

var snapshotactionsesResource = v1.SchemeGroupVersion.WithResource("snapshotactionses")

var snapshotactionsesKind = v1.SchemeGroupVersion.WithKind("SnapshotActions")

// Get takes name of the snapshotActions, and returns the corresponding snapshotActions object, and an error if there is any.
func (c *FakeSnapshotActionses) Get(ctx context.Context, name string, options metav1.GetOptions) (result *v1.SnapshotActions, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewGetAction(snapshotactionsesResource, c.ns, name), &v1.SnapshotActions{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1.SnapshotActions), err
}

// List takes label and field selectors, and returns the list of SnapshotActionses that match those selectors.
func (c *FakeSnapshotActionses) List(ctx context.Context, opts metav1.ListOptions) (result *v1.SnapshotActionsList, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewListAction(snapshotactionsesResource, snapshotactionsesKind, c.ns, opts), &v1.SnapshotActionsList{})

	if obj == nil {
		return nil, err
	}

	label, _, _ := testing.ExtractFromListOptions(opts)
	if label == nil {
		label = labels.Everything()
	}
	list := &v1.SnapshotActionsList{ListMeta: obj.(*v1.SnapshotActionsList).ListMeta}
	for _, item := range obj.(*v1.SnapshotActionsList).Items {
		if label.Matches(labels.Set(item.Labels)) {
			list.Items = append(list.Items, item)
		}
	}
	return list, err
}

// Watch returns a watch.Interface that watches the requested snapshotActionses.
func (c *FakeSnapshotActionses) Watch(ctx context.Context, opts metav1.ListOptions) (watch.Interface, error) {
	return c.Fake.
		InvokesWatch(testing.NewWatchAction(snapshotactionsesResource, c.ns, opts))

}

// Create takes the representation of a snapshotActions and creates it.  Returns the server's representation of the snapshotActions, and an error, if there is any.
func (c *FakeSnapshotActionses) Create(ctx context.Context, snapshotActions *v1.SnapshotActions, opts metav1.CreateOptions) (result *v1.SnapshotActions, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewCreateAction(snapshotactionsesResource, c.ns, snapshotActions), &v1.SnapshotActions{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1.SnapshotActions), err
}

// Update takes the representation of a snapshotActions and updates it. Returns the server's representation of the snapshotActions, and an error, if there is any.
func (c *FakeSnapshotActionses) Update(ctx context.Context, snapshotActions *v1.SnapshotActions, opts metav1.UpdateOptions) (result *v1.SnapshotActions, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateAction(snapshotactionsesResource, c.ns, snapshotActions), &v1.SnapshotActions{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1.SnapshotActions), err
}

// Delete takes name of the snapshotActions and deletes it. Returns an error if one occurs.
func (c *FakeSnapshotActionses) Delete(ctx context.Context, name string, opts metav1.DeleteOptions) error {
	_, err := c.Fake.
		Invokes(testing.NewDeleteActionWithOptions(snapshotactionsesResource, c.ns, name, opts), &v1.SnapshotActions{})

	return err
}

// DeleteCollection deletes a collection of objects.
func (c *FakeSnapshotActionses) DeleteCollection(ctx context.Context, opts metav1.DeleteOptions, listOpts metav1.ListOptions) error {
	action := testing.NewDeleteCollectionAction(snapshotactionsesResource, c.ns, listOpts)

	_, err := c.Fake.Invokes(action, &v1.SnapshotActionsList{})
	return err
}

// Patch applies the patch and returns the patched snapshotActions.
func (c *FakeSnapshotActionses) Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts metav1.PatchOptions, subresources ...string) (result *v1.SnapshotActions, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewPatchSubresourceAction(snapshotactionsesResource, c.ns, name, pt, data, subresources...), &v1.SnapshotActions{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1.SnapshotActions), err
}

// Apply takes the given apply declarative configuration, applies it and returns the applied snapshotActions.
func (c *FakeSnapshotActionses) Apply(ctx context.Context, snapshotActions *pranoykundudevv1.SnapshotActionsApplyConfiguration, opts metav1.ApplyOptions) (result *v1.SnapshotActions, err error) {
	if snapshotActions == nil {
		return nil, fmt.Errorf("snapshotActions provided to Apply must not be nil")
	}
	data, err := json.Marshal(snapshotActions)
	if err != nil {
		return nil, err
	}
	name := snapshotActions.Name
	if name == nil {
		return nil, fmt.Errorf("snapshotActions.Name must be provided to Apply")
	}
	obj, err := c.Fake.
		Invokes(testing.NewPatchSubresourceAction(snapshotactionsesResource, c.ns, *name, types.ApplyPatchType, data), &v1.SnapshotActions{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1.SnapshotActions), err
}
