/*
Copyright The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by client-gen. DO NOT EDIT.

package v1

import (
	"context"
	json "encoding/json"
	"fmt"
	"time"

	v1 "github.com/pranoyk/volume-snapshotter/pkg/apis/pranoykundu.dev/v1"
	pranoykundudevv1 "github.com/pranoyk/volume-snapshotter/pkg/client/applyconfiguration/pranoykundu.dev/v1"
	scheme "github.com/pranoyk/volume-snapshotter/pkg/client/clientset/versioned/scheme"
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	rest "k8s.io/client-go/rest"
)

// SnapshotActionsesGetter has a method to return a SnapshotActionsInterface.
// A group's client should implement this interface.
type SnapshotActionsesGetter interface {
	SnapshotActionses(namespace string) SnapshotActionsInterface
}

// SnapshotActionsInterface has methods to work with SnapshotActions resources.
type SnapshotActionsInterface interface {
	Create(ctx context.Context, snapshotActions *v1.SnapshotActions, opts metav1.CreateOptions) (*v1.SnapshotActions, error)
	Update(ctx context.Context, snapshotActions *v1.SnapshotActions, opts metav1.UpdateOptions) (*v1.SnapshotActions, error)
	Delete(ctx context.Context, name string, opts metav1.DeleteOptions) error
	DeleteCollection(ctx context.Context, opts metav1.DeleteOptions, listOpts metav1.ListOptions) error
	Get(ctx context.Context, name string, opts metav1.GetOptions) (*v1.SnapshotActions, error)
	List(ctx context.Context, opts metav1.ListOptions) (*v1.SnapshotActionsList, error)
	Watch(ctx context.Context, opts metav1.ListOptions) (watch.Interface, error)
	Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts metav1.PatchOptions, subresources ...string) (result *v1.SnapshotActions, err error)
	Apply(ctx context.Context, snapshotActions *pranoykundudevv1.SnapshotActionsApplyConfiguration, opts metav1.ApplyOptions) (result *v1.SnapshotActions, err error)
	SnapshotActionsExpansion
}

// snapshotActionses implements SnapshotActionsInterface
type snapshotActionses struct {
	client rest.Interface
	ns     string
}

// newSnapshotActionses returns a SnapshotActionses
func newSnapshotActionses(c *PranoykunduV1Client, namespace string) *snapshotActionses {
	return &snapshotActionses{
		client: c.RESTClient(),
		ns:     namespace,
	}
}

// Get takes name of the snapshotActions, and returns the corresponding snapshotActions object, and an error if there is any.
func (c *snapshotActionses) Get(ctx context.Context, name string, options metav1.GetOptions) (result *v1.SnapshotActions, err error) {
	result = &v1.SnapshotActions{}
	err = c.client.Get().
		Namespace(c.ns).
		Resource("snapshotactionses").
		Name(name).
		VersionedParams(&options, scheme.ParameterCodec).
		Do(ctx).
		Into(result)
	return
}

// List takes label and field selectors, and returns the list of SnapshotActionses that match those selectors.
func (c *snapshotActionses) List(ctx context.Context, opts metav1.ListOptions) (result *v1.SnapshotActionsList, err error) {
	var timeout time.Duration
	if opts.TimeoutSeconds != nil {
		timeout = time.Duration(*opts.TimeoutSeconds) * time.Second
	}
	result = &v1.SnapshotActionsList{}
	err = c.client.Get().
		Namespace(c.ns).
		Resource("snapshotactionses").
		VersionedParams(&opts, scheme.ParameterCodec).
		Timeout(timeout).
		Do(ctx).
		Into(result)
	return
}

// Watch returns a watch.Interface that watches the requested snapshotActionses.
func (c *snapshotActionses) Watch(ctx context.Context, opts metav1.ListOptions) (watch.Interface, error) {
	var timeout time.Duration
	if opts.TimeoutSeconds != nil {
		timeout = time.Duration(*opts.TimeoutSeconds) * time.Second
	}
	opts.Watch = true
	return c.client.Get().
		Namespace(c.ns).
		Resource("snapshotactionses").
		VersionedParams(&opts, scheme.ParameterCodec).
		Timeout(timeout).
		Watch(ctx)
}

// Create takes the representation of a snapshotActions and creates it.  Returns the server's representation of the snapshotActions, and an error, if there is any.
func (c *snapshotActionses) Create(ctx context.Context, snapshotActions *v1.SnapshotActions, opts metav1.CreateOptions) (result *v1.SnapshotActions, err error) {
	result = &v1.SnapshotActions{}
	err = c.client.Post().
		Namespace(c.ns).
		Resource("snapshotactionses").
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(snapshotActions).
		Do(ctx).
		Into(result)
	return
}

// Update takes the representation of a snapshotActions and updates it. Returns the server's representation of the snapshotActions, and an error, if there is any.
func (c *snapshotActionses) Update(ctx context.Context, snapshotActions *v1.SnapshotActions, opts metav1.UpdateOptions) (result *v1.SnapshotActions, err error) {
	result = &v1.SnapshotActions{}
	err = c.client.Put().
		Namespace(c.ns).
		Resource("snapshotactionses").
		Name(snapshotActions.Name).
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(snapshotActions).
		Do(ctx).
		Into(result)
	return
}

// Delete takes name of the snapshotActions and deletes it. Returns an error if one occurs.
func (c *snapshotActionses) Delete(ctx context.Context, name string, opts metav1.DeleteOptions) error {
	return c.client.Delete().
		Namespace(c.ns).
		Resource("snapshotactionses").
		Name(name).
		Body(&opts).
		Do(ctx).
		Error()
}

// DeleteCollection deletes a collection of objects.
func (c *snapshotActionses) DeleteCollection(ctx context.Context, opts metav1.DeleteOptions, listOpts metav1.ListOptions) error {
	var timeout time.Duration
	if listOpts.TimeoutSeconds != nil {
		timeout = time.Duration(*listOpts.TimeoutSeconds) * time.Second
	}
	return c.client.Delete().
		Namespace(c.ns).
		Resource("snapshotactionses").
		VersionedParams(&listOpts, scheme.ParameterCodec).
		Timeout(timeout).
		Body(&opts).
		Do(ctx).
		Error()
}

// Patch applies the patch and returns the patched snapshotActions.
func (c *snapshotActionses) Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts metav1.PatchOptions, subresources ...string) (result *v1.SnapshotActions, err error) {
	result = &v1.SnapshotActions{}
	err = c.client.Patch(pt).
		Namespace(c.ns).
		Resource("snapshotactionses").
		Name(name).
		SubResource(subresources...).
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(data).
		Do(ctx).
		Into(result)
	return
}

// Apply takes the given apply declarative configuration, applies it and returns the applied snapshotActions.
func (c *snapshotActionses) Apply(ctx context.Context, snapshotActions *pranoykundudevv1.SnapshotActionsApplyConfiguration, opts metav1.ApplyOptions) (result *v1.SnapshotActions, err error) {
	if snapshotActions == nil {
		return nil, fmt.Errorf("snapshotActions provided to Apply must not be nil")
	}
	patchOpts := opts.ToPatchOptions()
	data, err := json.Marshal(snapshotActions)
	if err != nil {
		return nil, err
	}
	name := snapshotActions.Name
	if name == nil {
		return nil, fmt.Errorf("snapshotActions.Name must be provided to Apply")
	}
	result = &v1.SnapshotActions{}
	err = c.client.Patch(types.ApplyPatchType).
		Namespace(c.ns).
		Resource("snapshotactionses").
		Name(*name).
		VersionedParams(&patchOpts, scheme.ParameterCodec).
		Body(data).
		Do(ctx).
		Into(result)
	return
}
