/*
Copyright The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by informer-gen. DO NOT EDIT.

package v1

import (
	"context"
	time "time"

	pranoykundudevv1 "github.com/pranoyk/volume-snapshotter/pkg/apis/pranoykundu.dev/v1"
	versioned "github.com/pranoyk/volume-snapshotter/pkg/client/clientset/versioned"
	internalinterfaces "github.com/pranoyk/volume-snapshotter/pkg/client/informers/externalversions/internalinterfaces"
	v1 "github.com/pranoyk/volume-snapshotter/pkg/client/listers/pranoykundu.dev/v1"
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	runtime "k8s.io/apimachinery/pkg/runtime"
	watch "k8s.io/apimachinery/pkg/watch"
	cache "k8s.io/client-go/tools/cache"
)

// SnapshotActionInformer provides access to a shared informer and lister for
// SnapshotActions.
type SnapshotActionInformer interface {
	Informer() cache.SharedIndexInformer
	Lister() v1.SnapshotActionLister
}

type snapshotActionInformer struct {
	factory          internalinterfaces.SharedInformerFactory
	tweakListOptions internalinterfaces.TweakListOptionsFunc
	namespace        string
}

// NewSnapshotActionInformer constructs a new informer for SnapshotAction type.
// Always prefer using an informer factory to get a shared informer instead of getting an independent
// one. This reduces memory footprint and number of connections to the server.
func NewSnapshotActionInformer(client versioned.Interface, namespace string, resyncPeriod time.Duration, indexers cache.Indexers) cache.SharedIndexInformer {
	return NewFilteredSnapshotActionInformer(client, namespace, resyncPeriod, indexers, nil)
}

// NewFilteredSnapshotActionInformer constructs a new informer for SnapshotAction type.
// Always prefer using an informer factory to get a shared informer instead of getting an independent
// one. This reduces memory footprint and number of connections to the server.
func NewFilteredSnapshotActionInformer(client versioned.Interface, namespace string, resyncPeriod time.Duration, indexers cache.Indexers, tweakListOptions internalinterfaces.TweakListOptionsFunc) cache.SharedIndexInformer {
	return cache.NewSharedIndexInformer(
		&cache.ListWatch{
			ListFunc: func(options metav1.ListOptions) (runtime.Object, error) {
				if tweakListOptions != nil {
					tweakListOptions(&options)
				}
				return client.PranoykunduV1().SnapshotActions(namespace).List(context.TODO(), options)
			},
			WatchFunc: func(options metav1.ListOptions) (watch.Interface, error) {
				if tweakListOptions != nil {
					tweakListOptions(&options)
				}
				return client.PranoykunduV1().SnapshotActions(namespace).Watch(context.TODO(), options)
			},
		},
		&pranoykundudevv1.SnapshotAction{},
		resyncPeriod,
		indexers,
	)
}

func (f *snapshotActionInformer) defaultInformer(client versioned.Interface, resyncPeriod time.Duration) cache.SharedIndexInformer {
	return NewFilteredSnapshotActionInformer(client, f.namespace, resyncPeriod, cache.Indexers{cache.NamespaceIndex: cache.MetaNamespaceIndexFunc}, f.tweakListOptions)
}

func (f *snapshotActionInformer) Informer() cache.SharedIndexInformer {
	return f.factory.InformerFor(&pranoykundudevv1.SnapshotAction{}, f.defaultInformer)
}

func (f *snapshotActionInformer) Lister() v1.SnapshotActionLister {
	return v1.NewSnapshotActionLister(f.Informer().GetIndexer())
}
